
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Course;

CREATE TABLE Book (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    isbn VARCHAR(100) NOT NULL
);

CREATE TABLE Tag (
    id SERIAL PRIMARY KEY,
    tag VARCHAR(100) NOT NULL,
    tipId INTEGER
);

CREATE TABLE Course (
    id SERIAL PRIMARY KEY,
    Course VARCHAR(100) NOT NULL,
    tipId INTEGER
);